apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "cdi.labels" . | nindent 4 }}
    cdi.kubevirt.io: {{ include "cdi.operator.name" . }}
    name: {{ include "cdi.operator.name" . }}
    np.kubevirt.io/allow-access-cluster-services: "true"
    operator.cdi.kubevirt.io: ""
    prometheus.cdi.kubevirt.io: "true"
  name: {{ include "cdi.operator.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.operator.replicas }}
  selector:
    matchLabels:
      name: {{ include "cdi.operator.name" . }}
      operator.cdi.kubevirt.io: ""
  strategy: {}
  template:
    metadata:
      annotations:
        openshift.io/required-scc: restricted-v2
      labels:
        {{- include "cdi.selectorLabels" . | nindent 8 }}
        cdi.kubevirt.io: {{ include "cdi.operator.name" . }}
        name: {{ include "cdi.operator.name" . }}
        np.kubevirt.io/allow-access-cluster-services: "true"
        operator.cdi.kubevirt.io: ""
        prometheus.cdi.kubevirt.io: "true"
    spec:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: cdi.kubevirt.io
                  operator: In
                  values:
                  - {{ include "cdi.operator.name" . }}
              topologyKey: kubernetes.io/hostname
            weight: 1
      containers:
      - env:
        - name: DEPLOY_CLUSTER_RESOURCES
          value: "true"
        - name: OPERATOR_VERSION
          value: {{ .Chart.AppVersion }}
        - name: CONTROLLER_IMAGE
          value: {{ default .Values.images.controller.registry .Values.global.imageRegistry }}/{{ .Values.images.controller.repository }}:{{ default .Chart.AppVersion .Values.images.controller.tag }}
        - name: IMPORTER_IMAGE
          value: {{ default .Values.images.importer.registry .Values.global.imageRegistry }}/{{ .Values.images.importer.repository }}:{{ default .Chart.AppVersion .Values.images.importer.tag }}
        - name: CLONER_IMAGE
          value: {{ default .Values.images.cloner.registry .Values.global.imageRegistry }}/{{ .Values.images.cloner.repository }}:{{ default .Chart.AppVersion .Values.images.cloner.tag }}
        - name: OVIRT_POPULATOR_IMAGE
          value: {{ default .Values.images.importer.registry .Values.global.imageRegistry }}/{{ .Values.images.importer.repository }}:{{ default .Chart.AppVersion .Values.images.importer.tag }}
        - name: APISERVER_IMAGE
          value: {{ default .Values.images.apiserver.registry .Values.global.imageRegistry }}/{{ .Values.images.apiserver.repository }}:{{ default .Chart.AppVersion .Values.images.apiserver.tag }}
        - name: UPLOAD_SERVER_IMAGE
          value: {{ default .Values.images.uploadServer.registry .Values.global.imageRegistry }}/{{ .Values.images.uploadServer.repository }}:{{ default .Chart.AppVersion .Values.images.uploadServer.tag }}
        - name: UPLOAD_PROXY_IMAGE
          value: {{ default .Values.images.uploadProxy.registry .Values.global.imageRegistry }}/{{ .Values.images.uploadProxy.repository }}:{{ default .Chart.AppVersion .Values.images.uploadProxy.tag }}
        - name: VERBOSITY
          value: {{ .Values.operator.verbosity | quote }}
        - name: PULL_POLICY
          value: {{ .Values.operator.image.pullPolicy }}
        - name: MONITORING_NAMESPACE
        image: {{ include "cdi.image" . }}
        imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8444
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 10
        name: {{ include "cdi.operator.name" . }}
        ports:
        - containerPort: 8443
          name: metrics
          protocol: TCP
        - containerPort: 8444
          name: health
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8444
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 10
        {{- with .Values.operator.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.operator.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
      {{- with .Values.operator.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cdi.operator.name" . }}
