apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "cdi.labels" . | nindent 4 }}
    operator.cdi.kubevirt.io: ""
  name: {{ include "cdi.operator.name" . }}
  namespace: {{ .Release.Namespace }}
