apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubevirt.io: ""
    pod-security.kubernetes.io/enforce: "privileged"
    {{- include "kubevirt.labels" . | nindent 4 }}
  name: {{ .Release.Namespace }}
