operator:
  podSecurityContext:
    runAsUser: 65534
    runAsGroup: 65534
    fsGroup: 65534
  resources:
    limits:
      cpu: 1
      memory: 512Mi
  customizeComponents:
    patches:
      - patch: '{"metadata":{"annotations":{"prometheus.io/probe_skip":"true"}}}'
        type: strategic
        resourceName: kubevirt-prometheus-metrics
        resourceType: Service
      - patch: '{"metadata":{"annotations":{"prometheus.io/probe_skip":"true"}}}'
        type: strategic
        resourceName: virt-exportproxy
        resourceType: Service
  extraConfig:
    imageTag: '{{ .Chart.AppVersion }}'
